add tip generator
dethcrypto/dethtools pull request #44
Opened 2022-04-04 10:53 UTC by 7sne

2022-04-04 11:17 UTC, hasparus requested changes
🙈

2022-04-04 12:29 UTC, LogvinovLeon reviewed
I like the idea in general, before merging - let's add actual tips and add to other pages

2022-04-04 12:54 UTC, hasparus commented on src/components/Tips.tsx
> +const tips: { [key in TipCategory]: string[] } = {
I'd argue this dict is redundant.

Imagine we have a thousand pages.
We'd have to keep all tips here in a huge dictionary, which gets bundled with every other page.
To update a tip, I have to open a page, copy it's ID and then go to this file to look up the ID.

Wouldn't it be easier to keep the calculator tips in the calculator page and the decoder tips in the decoder page?

---

A good rule of thumb for an answer to question "Should I keep it in XML or should I keep it in JSON?" is "Are you building an user interface, or is it serialized data to store or send over the wire?"

2022-04-06 12:13 UTC, hasparus approved these changes

2022-04-06 12:24 UTC, merged

2022-04-06 12:24 UTC, hasparus commented
Merging to avoid more conflicts, we can add more tips later.