Fixes before release
dethcrypto/dethtools pull request #54
Opened 2022-04-19 12:30 UTC by 7sne

2022-04-21 22:51 UTC, krzkaczor requested changes

2022-04-21 22:51 UTC, krzkaczor commented on pages/calldata-decoder.page.tsx
> +      void handleDecodeCalldata();
void not needed anymore

2022-04-21 22:51 UTC, krzkaczor commented on pages/calldata-decoder.page.tsx
> +      setError('a');
please provide some error message

2022-04-22 09:19 UTC, LogvinovLeon approved these changes

2022-04-25 10:16 UTC, closed without merging