Unix epoch utc conversion
dethcrypto/dethtools pull request #77
Opened 2022-07-19 16:07 UTC by 7sne

2022-07-22 17:14 UTC, LogvinovLeon requested changes
Hi. Great work in general. Left a lot of comments, but some of them are about the same. In general – it works and it's rather clean.

2022-07-22 17:14 UTC, LogvinovLeon commented on src/components/CurrentEpochTime.tsx
> +}
Do I get it right, that this is better than normal `setInterval`, because it doesn't fire after component unmount?

2022-07-22 17:14 UTC, LogvinovLeon commented on src/components/CurrentEpochTime.tsx
> +  );
Please stop calling state "state" when avoidable. What is this? `timestamp`? `timestampMillis`?

2022-07-22 17:14 UTC, LogvinovLeon commented on src/lib/decodeBySigHash.test.ts
> +  afterEach(() => {
Same

2022-07-22 17:14 UTC, LogvinovLeon commented on src/lib/decodeBySigHash.test.ts
> +  afterEach(() => {
Same

2022-07-22 17:14 UTC, LogvinovLeon commented on src/lib/decodeBySigHash.ts
> +  EventProps: async (sigHash: string) => {
Why the name change? Why not EventSignatures? What are even EventProps? I know events have data, topics, names, signatures. But props?

2022-07-22 17:14 UTC, LogvinovLeon commented on src/lib/decodeBySigHash.ts
> -};
Well, this is still needed if we want our optimistic fetch to work. now it's a regression. Unfortunately we don't have a test for it (my bad). Would be great to have it. And a great way to check mocks. Will look smth like:
```
click()
assert.calledOnce()
click()
assert.called0Times()
```

2022-07-22 17:14 UTC, LogvinovLeon commented on src/lib/decodeBySigHash.ts
> +interface FourBytes {
Is this the best name?
`FourBytesReponseEntry`, `Signature`, `SignatureDescription`.

2022-07-22 17:14 UTC, LogvinovLeon commented on src/misc/unsafeEntries.ts
> +export function unsafeEntries<T>(obj: T): Entries<T> {
That is awesome!

2022-07-22 17:24 UTC, 7sne commented on pages/calldata-decoder.test.tsx
> +    sinon.restore(); // Unwraps the spy
Yeah, right.. Wow. I just got lied to on the stack overflow. :(

2022-07-22 17:27 UTC, 7sne commented on src/misc/unsafeEntries.ts
> +export function unsafeEntries<T>(obj: T): Entries<T> {
Screw safety! Embrace types!

2022-07-22 17:36 UTC, 7sne commented on pages/calldata-decoder.page.tsx
> +                await fetch4BytesBy.Signatures(sigHash);
Right. I totally forgot about it. The error is actually consumed before so the try/catch block is unnecessary.

2022-07-22 17:39 UTC, 7sne commented on pages/calldata-decoder.page.tsx
> +                await fetch4BytesBy.Signatures(sigHash);
And, the void keyword is imo somewhat strange, the void operator means that we don't want to get the expr. result and right it's cool in this case, but I would rather use the proper await keyword so it's clear and not confusing that we're calling something async here.

2022-07-22 17:42 UTC, 7sne commented on pages/calldata-decoder.test.tsx
> +      { timeout: 300 },
To be fair we don't need the timeout configs anywhere now, I just forgot about it. :(

2022-07-25 09:31 UTC, LogvinovLeon commented on pages/calldata-decoder.page.tsx
> +                await fetch4BytesBy.Signatures(sigHash);
I think void here does exactly what you want. It indicates that we call, but don't wait.
Using `await` on the other hand suggests, that we do wait for the end of the operation.

2022-07-25 09:32 UTC, LogvinovLeon approved these changes
LGTM except the void comment

2022-07-25 09:35 UTC, merged